SQLALCHEMY_DATABASE_URI = 'sqlite:///flask_blog.db'
SQLALCHEMY_TRACK_MODIFICATIONS = True
DEBUG = True
SECRET_KEY = 'secret key'
USERNAME = 'test'
PASSWORD = 'test'
GUESTNAME='guest'
GUESTPASSWORD='gexam'
